Numpy

In [2]:
import numpy as np

In [3]:
#numpy is used to working with arrays
#numpy is a numerical python

In [4]:
z = np.zeros(13)

In [5]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
type(z)

numpy.ndarray

In [9]:
z = z.astype(int)   # this converts to int - typecasting

In [ ]:
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
z.ndim   # this gives the dimension of an array

1

In [13]:
#   No.of brackets = Dimensions

In [14]:
s = np.array([[1,2,2,2,3,4,5,6]])
s

array([[1, 2, 2, 2, 3, 4, 5, 6]])

In [15]:
s.ndim

2

In [17]:
two_dim = np.array([[1,3,4,5], [2,5,6,7]])
two_dim

array([[1, 3, 4, 5],
       [2, 5, 6, 7]])

In [19]:
two_dim.ndim

2

In [20]:
sample = np.array([[4,5,67,7], [4,1,9]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [21]:
#both matrices should have same number of elements - in numpy version 2.4.4
#but in 1.18.1 will not give error

In [22]:
two_dim

array([[1, 3, 4, 5],
       [2, 5, 6, 7]])

In [24]:
two_dim.shape     #rows * columns

(2, 4)

In [25]:
#when u multiply the shape elements - 2*4 = 8 -> we will get the number of elements in an array

In [26]:
#convert to 1d array

In [28]:
two_dim.reshape(8, )   #here 8 * null = 8 -> 8 elements fit in sngle array

array([1, 3, 4, 5, 2, 5, 6, 7])

In [29]:
#convert to 3d array

In [ ]:
two_dim.reshape(2,2,2)
#(2 rows, 2 cols, 2 sets)

array([[[1, 3],
        [4, 5]],

       [[2, 5],
        [6, 7]]])

In [31]:
two_dim.reshape(1,2,4)

array([[[1, 3, 4, 5],
        [2, 5, 6, 7]]])

In [32]:
#the blocks are just representing the UI like - 4,2,1 - 1,2,4 the block ui are just a visual representation
#of ui, both are same dim, so sont worry about the block, nderstand the dim only

In [33]:
# Indexing

In [34]:
a = np.array([[2,5,6], [6,5,8], [8,9,5]])
a

array([[2, 5, 6],
       [6, 5, 8],
       [8, 9, 5]])

In [35]:
a[0][1]

np.int64(5)

In [36]:
a[0][2]

np.int64(6)

In [37]:
a[-1][-1]

np.int64(5)

In [38]:
a[-2][-1]

np.int64(8)

In [39]:
a[1:, 1:]

array([[5, 8],
       [9, 5]])

In [41]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

In [42]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
arr[0, 1, 2]

np.int64(6)

In [44]:
arr[1,-1]

array([10, 11, 12])

In [45]:
arr[1,-2]

array([7, 8, 9])

In [47]:
arr[1:]

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr[0:1]

array([[[1, 2, 3],
        [4, 5, 6]]])