In [1]:
import numpy as np

In [2]:
a = np.array([[2,5,6], [6,5,8], [8,9,5]])
a

array([[2, 5, 6],
       [6, 5, 8],
       [8, 9, 5]])

In [3]:
a[0:, 2:]

array([[6],
       [8],
       [5]])

In [4]:
a[:2]

array([[2, 5, 6],
       [6, 5, 8]])

In [5]:
a[0:, 2:].reshape(3, )

array([6, 8, 5])

In [6]:
lin = np.linspace(0, 20, 10)
lin

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [7]:
#it will start from 0 to 20 and 10 elements ni ee 0 to 20 madyalo place chestadi with equal spaces

In [8]:
lin = np.linspace(0,20,20)
lin

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

In [9]:
lin.max()

np.float64(20.0)

In [10]:
lin.min()

np.float64(0.0)

In [11]:
lin.argmax()

np.int64(19)

In [12]:
lin.argmin()

np.int64(0)

In [13]:
a

array([[2, 5, 6],
       [6, 5, 8],
       [8, 9, 5]])

In [14]:
a.max()

np.int64(9)

In [15]:
a.min()

np.int64(2)

In [16]:
a.argmax()

np.int64(7)

In [17]:
a.argmin()

np.int64(0)

In [18]:
a.mean()

np.float64(6.0)

In [20]:
#arange is also like range/linspace -> but it will have step and slice like range

In [21]:
val = np.arange(20, 100, 10)  #start, stop, step

In [22]:
val

array([20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
val * 2

array([ 40,  60,  80, 100, 120, 140, 160, 180])

In [24]:
val

array([20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
np.where(val == 70)

(array([5]),)

In [26]:
a

array([[2, 5, 6],
       [6, 5, 8],
       [8, 9, 5]])

In [27]:
np.where(a==8)

(array([1, 2]), array([2, 0]))

In [28]:
a.transpose()

array([[2, 6, 8],
       [5, 5, 9],
       [6, 8, 5]])

In [29]:
dir(val)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__